---
- hosts: consul_servers,clients
  become: yes
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
    - name: add group consul
      group: name='consul'
    - name: add consul user
      user: name='consul' groups="consul"
    - name: Creates data dir
      file:
        path: '{{item["mount_path"]}}/{{item["name"]}}'
        state: directory
        owner: "{{item['owner']}}"
        group: "{{item['owner']}}"
        mode: 0755
      loop: "{{ mounts }}"
    - name: links data dir
      file:
        src: '{{item["mount_path"]}}/{{item["name"]}}'
        dest: "{{item['path']}}"
        state: link
        owner: "{{item['owner']}}"
        group: "{{item['owner']}}"
      loop: "{{ mounts }}"
- hosts: all 
  become: yes
  tasks:
    # - name: Set authorized key taken from file
    #   authorized_key:
    #     user: root
    #     state: present
    #     key: "{{ lookup('file', 'id_rsa.pub') }}"
    - name: Add HCP signing key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add Docker signing key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add hcp into sources list
      ansible.builtin.apt_repository:
        repo: deb https://apt.releases.hashicorp.com jammy main
        state: present
    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable 
        state: present
    - name: ensure apt cache is updated
      action: apt update_cache=yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
    - name: ensure all software is installed
      action: apt name={{item}}
      with_items:
        - wget
        - curl
        - ca-certificates
        - gnupg
        - lsb-release
        - nomad
        - consul
        - zip
        - tar
        - vault
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - software-properties-common
        - apt-transport-https
        - prometheus-node-exporter-collectors
    - name: add group consul
      group: name='consul'
    - name: add consul user
      user: name='consul' groups="consul"
    - name: Creates config dir
      file:
        path: /etc/consul.d
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: Creates certs dir
      file:
        path: /etc/consul.d/certs
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: copy consul agent ca 
      copy:
        src: secrets/consul/consul-agent-ca.pem
        dest: /etc/consul.d/certs/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0755
    - name: copy consul client key
      copy:
        src: secrets/consul/consul-agent-ca-key.pem
        dest: /etc/consul.d/certs/consul-agent-ca-key.pem
        owner: consul
        group: consul
        mode: 0755
    - name: copy consul client key
      copy:
        src: consul/resolved.conf
        dest: /etc/systemd/resolved.conf
        mode: 0755
    - name: copy consul service file
      copy:
        src: consul/consul.service
        dest: /etc/systemd/system/consul.service
        mode: 0755
    - name: copy consul exporter service
      copy:
        src: consul/consul-exporter.service
        dest: /etc/systemd/system/consul-exporter.service
        mode: 0755
    - name: copy consul_exporter
      copy:
        src: consul/install-exporter.sh
        dest: '{{cloud_provider_config.sudo_dir}}/install-exporter.sh'
        mode: 0755
    - name: Install consul exporter
      ansible.builtin.command: '{{cloud_provider_config.sudo_dir}}/install-exporter.sh'
    - name: Download cni plugin
      ansible.builtin.command: curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
    - name: Creates cni dir
      file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: 0755      
    - name: Install CNI plugin
      ansible.builtin.command: tar -C /opt/cni/bin -xzf cni-plugins.tgz
    - name: setup CNI plugin
      ansible.builtin.command: echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables && echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables && echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables
    - name: start node-exporter on boot
      ansible.builtin.systemd:
        enabled: yes
        name: prometheus-node-exporter
    - name: Restart node-exporter service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: prometheus-node-exporter
 
