on:
  pull_request:
    branches:
      - main
name: Test & Lint
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name: Install dependencies
      run: |- 
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install -y consul nomad vault terraform software-properties-common
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Install CFSSL
      run: |- 
        go install github.com/cloudflare/cfssl/cmd/...@latest
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test ./... -race
    - name: lint
      uses: golangci/golangci-lint-action@v3.3.0
      with:
        version: v1.50.1
        args: --timeout=2m
