on: [push, pull_request]
name: Test & Lint
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test ./... -race
    - name: lint
      uses: golangci/golangci-lint-action@v3.3.0
      with:
        version: v1.49.0
        args: --timeout=2m
